export function ConselorApprovalData() {
  return {
    data: [
      {
        id: 1,
        firstName: "Alice",
        lastName: "Johnson",
        email: "alice.j@example.com",
        status: "Pending Review",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-29",
      },
      {
        id: 2,
        firstName: "Bob",
        lastName: "Williams",
        email: "bob.w@example.com",
        status: "Approved",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-28",
      },
      {
        id: 3,
        firstName: "Charlie",
        lastName: "Brown",
        email: "charlie.b@example.com",
        status: "Pending Review", // Changed from "Under Review"
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-27",
      },
      {
        id: 4,
        firstName: "Diana",
        lastName: "Prince",
        email: "diana.p@example.com",
        status: "Rejected",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-26",
      },
      {
        id: 5,
        firstName: "Eve",
        lastName: "Adams",
        email: "eve.a@example.com",
        status: "Pending Review",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-25",
      },
      {
        id: 6,
        firstName: "Frank",
        lastName: "White",
        email: "frank.w@example.com",
        status: "Approved",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-24",
      },
      {
        id: 7,
        firstName: "Grace",
        lastName: "Taylor",
        email: "grace.t@example.com",
        status: "Pending Review", // Changed from "Under Review"
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-23",
      },
      {
        id: 8,
        firstName: "Henry",
        lastName: "Green",
        email: "henry.g@example.com",
        status: "Pending Review",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-22",
      },
      {
        id: 9,
        firstName: "Ivy",
        lastName: "King",
        email: "ivy.k@example.com",
        status: "Rejected",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-21",
      },
      {
        id: 10,
        firstName: "Jack",
        lastName: "Lee",
        email: "jack.l@example.com",
        status: "Approved",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-20",
      },
      {
        id: 11,
        firstName: "Karen",
        lastName: "Hall",
        email: "karen.h@example.com",
        status: "Pending Review",
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-19",
      },
      {
        id: 12,
        firstName: "Liam",
        lastName: "Scott",
        email: "liam.s@example.com",
        status: "Pending Review", // Changed from "Under Review"
        image: "/placeholder.svg?height=40&width=40",
        uploadedAt: "2025-07-18",
      },
    ],
  }
}
