import { Plan } from "./type";

export const plans: Plan[] = [
  {
    id: "basic",
    tag: "Basic",
    name: "Basic Plan",
    description: "Perfect for individuals starting their spiritual journey",
    monthlyPrice: 15,
    yearlyPrice: 150,
    discount: "17% discount",
    monthlyTokenCount: 800,
    tokenRolloverEnabled: false,
    features: [
      { text: "Up to 2 sessions per month", included: true },
      { text: "Email support", included: true },
      { text: "No session recording", included: false },
      { text: "Basic AI transcription", included: true },
      { text: "Mobile app access", included: true },
      { text: "Limited counselor selection", included: false },
    ],
    statusActive: true,
    currentSubscribers: 1245,
  },
  {
    id: "premium",
    tag: "Premium",
    name: "Premium Plan",
    description: "Enhanced features for regular spiritual counseling",
    monthlyPrice: 75,
    yearlyPrice: 750,
    monthlyTokenCount: 1500,
    tokenRolloverEnabled: true,
    rolloverPercentage: 50,
    maxRolloverTokens: 750,
    features: [
      { text: "Up to 6 sessions per month", included: true },
      { text: "Session recordings", included: true },
      { text: "24/7 chat support", included: true },
      { text: "Limited to video sessions", included: false },
      { text: "Advanced AI analysis", included: true },
      { text: "Priority counselor selection", included: true },
      { text: "Progress tracking", included: true },
    ],
    statusActive: true,
    currentSubscribers: 1156,
  },
  {
    id: "professional",
    tag: "Professional",
    name: "Professional Plan",
    description: "Comprehensive solution for intensive spiritual work",
    monthlyPrice: 120,
    yearlyPrice: 1200,
    discount: "17% discount",
    monthlyTokenCount: 2500,
    tokenRolloverEnabled: true,
    rolloverPercentage: 75,
    maxRolloverTokens: 1875,
    features: [
      { text: "Unlimited sessions", included: true },
      { text: "Session recordings & transcripts", included: true },
      { text: "Priority support", included: true },
      { text: "Premium AI Insights", included: true },
      { text: "Dedicated counselor matching", included: true },
      { text: "Advanced analytics", included: true },
    ],
    statusActive: true,
    currentSubscribers: 446,
  },
]
