export function getKpiSubscriptionData() {
  return {
    subscriptions: [
      {
        id: "sub-001",
        userId: "user-001",
        userName: "María González",
        planId: "premium",
        planName: "Premium",
        startDate: "2024-01-01",
        endDate: null,
        status: "Active",
        monthlyRevenue: 75,
        tokensUsed: 1200,
        monthlyAllocation: 1500,
      },
      {
        id: "sub-002",
        userId: "user-002",
        userName: "Carlos Ruiz",
        planId: "basic",
        planName: "Basic",
        startDate: "2024-01-05",
        endDate: null,
        status: "Active",
        monthlyRevenue: 15,
        tokensUsed: 700,
        monthlyAllocation: 800,
      },
      {
        id: "sub-003",
        userId: "user-003",
        userName: "Luis Martínez",
        planId: "premium",
        planName: "Premium",
        startDate: "2023-12-10",
        endDate: null,
        status: "Active",
        monthlyRevenue: 75,
        tokensUsed: 1000,
        monthlyAllocation: 1500,
      },
      {
        id: "sub-004",
        userId: "user-004",
        userName: "Ana Rodríguez",
        planId: "basic",
        planName: "Basic",
        startDate: "2024-01-15",
        endDate: "2024-02-15",
        status: "Cancelled",
        monthlyRevenue: 15,
        tokensUsed: 300,
        monthlyAllocation: 800,
      },
      {
        id: "sub-005",
        userId: "user-005",
        userName: "Pedro Sánchez",
        planId: "professional",
        planName: "Professional",
        startDate: "2024-01-20",
        endDate: null,
        status: "Active",
        monthlyRevenue: 120,
        tokensUsed: 2000,
        monthlyAllocation: 2500,
      },
      {
        id: "sub-006",
        userId: "user-006",
        userName: "Sofía Vargas",
        planId: "basic",
        planName: "Basic",
        startDate: "2023-11-01",
        endDate: "2024-01-31",
        status: "Expired",
        monthlyRevenue: 15,
        tokensUsed: 600,
        monthlyAllocation: 800,
      },
      {
        id: "sub-007",
        userId: "user-007",
        userName: "Diego Herrera",
        planId: "premium",
        planName: "Premium",
        startDate: "2024-02-01",
        endDate: null,
        status: "Active",
        monthlyRevenue: 75,
        tokensUsed: 500,
        monthlyAllocation: 1500,
      },
      {
        id: "sub-008",
        userId: "user-008",
        userName: "Elena Castro",
        planId: "basic",
        planName: "Basic",
        startDate: "2024-02-05",
        endDate: null,
        status: "Active",
        monthlyRevenue: 15,
        tokensUsed: 400,
        monthlyAllocation: 800,
      },
      {
        id: "sub-009",
        userId: "user-009",
        userName: "Gabriel Flores",
        planId: "professional",
        planName: "Professional",
        startDate: "2024-02-10",
        endDate: null,
        status: "Active",
        monthlyRevenue: 120,
        tokensUsed: 1800,
        monthlyAllocation: 2500,
      },
      {
        id: "sub-010",
        userId: "user-010",
        userName: "Isabel Gómez",
        planId: "basic",
        planName: "Basic",
        startDate: "2024-02-15",
        endDate: null,
        status: "Active",
        monthlyRevenue: 15,
        tokensUsed: 300,
        monthlyAllocation: 800,
      },
    ],
  }
}
