import { Users, Clock, Zap, TrendingUp } from "lucide-react"

export function getSessionData() {
  return {
    stats: [
      {
        title: "Total Sessions",
        value: "7",
        icon: Users,
        color: "text-blue-500",
      },
      {
        title: "Avg Duration",
        value: "52 min",
        icon: Clock,
        color: "text-green-500",
      },
      {
        title: "Total Tokens Used",
        value: "6,049",
        icon: Zap,
        color: "text-purple-500",
      },
      {
        title: "Completion Rate",
        value: "71%",
        icon: TrendingUp,
        color: "text-orange-500",
      },
    ],
    sessions: [
      {
        id: "SES-001",
        client: "María González",
        counselor: "Dr. Ana López",
        date: "2024-01-30",
        time: "10:00 AM",
        duration: "60 min",
        actualDuration: "58 min",
        status: "Completed",
        tokensUsed: 1,
        tokenLimit: 1500,
        aiUsageEnabled: true,
        aiTokensTotal: 892,
        aiTokensActual: 355,
      },
      {
        id: "SES-002",
        client: "Carlos Ruiz",
        counselor: "Dra. Carmen Silva",
        date: "2024-01-30",
        time: "2:00 PM",
        duration: "45 min",
        actualDuration: "47 min",
        status: "Completed",
        tokensUsed: 1,
        tokenLimit: 1200,
        aiUsageEnabled: true,
        aiTokensTotal: 654,
        aiTokensActual: 269,
      },
      {
        id: "SES-003",
        client: "Laura Pérez",
        counselor: "Dr. Juan García",
        date: "2024-01-29",
        time: "11:30 AM",
        duration: "75 min",
        actualDuration: "70 min",
        status: "Pending",
        tokensUsed: 2,
        tokenLimit: 1000,
        aiUsageEnabled: false,
        aiTokensTotal: 0,
        aiTokensActual: 0,
      },
      {
        id: "SES-004",
        client: "Pedro Sánchez",
        counselor: "Dra. Elena Torres",
        date: "2024-01-28",
        time: "9:00 AM",
        duration: "30 min",
        actualDuration: "30 min",
        status: "Completed",
        tokensUsed: 2,
        tokenLimit: 300,
        aiUsageEnabled: true,
        aiTokensTotal: 150,
        aiTokensActual: 100,
      },
      {
        id: "SES-005",
        client: "Ana Martínez",
        counselor: "Dr. Miguel Ángel",
        date: "2024-01-27",
        time: "4:00 PM",
        duration: "90 min",
        actualDuration: "85 min",
        status: "Cancelled",
        tokensUsed: 0,
        tokenLimit: 0,
        aiUsageEnabled: false,
        aiTokensTotal: 0,
        aiTokensActual: 0,
      },
      {
        id: "SES-006",
        client: "Sofía Vargas",
        counselor: "Dra. Isabel Castro",
        date: "2024-01-26",
        time: "1:00 PM",
        duration: "60 min",
        actualDuration: "60 min",
        status: "Completed",
        tokensUsed: 2,
        tokenLimit: 1200,
        aiUsageEnabled: true,
        aiTokensTotal: 700,
        aiTokensActual: 400,
      },
      {
        id: "SES-007",
        client: "Diego Herrera",
        counselor: "Dr. Ricardo Soto",
        date: "2024-01-25",
        time: "10:00 AM",
        duration: "45 min",
        actualDuration: "40 min",
        status: "Completed",
        tokensUsed: 2,
        tokenLimit: 1000,
        aiUsageEnabled: true,
        aiTokensTotal: 500,
        aiTokensActual: 300,
      },
    ],
  }
}
