export function getUserTokenData() {
  return {
    users: [
      {
        id: "user-001",
        name: "María González",
        email: "maria.gonzalez@email.com",
        plan: "Premium",
        currentTokens: 3,
        tokenStatus: "Normal",
        monthlyAllocation: 4,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-002",
        name: "Carlos Ruiz",
        email: "carlos.ruiz@email.com",
        plan: "Basic",
        currentTokens: 0,
        tokenStatus: "Empty",
        monthlyAllocation: 2,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-003",
        name: "Luis Martínez",
        email: "luis.martinez@email.com",
        plan: "Premium",
        currentTokens: 6,
        tokenStatus: "Overflow",
        overflowAmount: 2,
        monthlyAllocation: 4,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-004",
        name: "Ana Rodríguez",
        email: "ana.rodriguez@email.com",
        plan: "Basic",
        currentTokens: 1,
        tokenStatus: "Low",
        monthlyAllocation: 2,
        status: "Suspended",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-005",
        name: "Pedro Sánchez",
        email: "pedro.sanchez@email.com",
        plan: "Premium",
        currentTokens: 2,
        tokenStatus: "Normal",
        monthlyAllocation: 4,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-006",
        name: "Sofía Vargas",
        email: "sofia.vargas@email.com",
        plan: "Basic",
        currentTokens: 5,
        tokenStatus: "Normal",
        monthlyAllocation: 5,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-007",
        name: "Diego Herrera",
        email: "diego.herrera@email.com",
        plan: "Premium",
        currentTokens: 0,
        tokenStatus: "Empty",
        monthlyAllocation: 3,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-008",
        name: "Elena Castro",
        email: "elena.castro@email.com",
        plan: "Basic",
        currentTokens: 1,
        tokenStatus: "Low",
        monthlyAllocation: 2,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-009",
        name: "Gabriel Flores",
        email: "gabriel.flores@email.com",
        plan: "Premium",
        currentTokens: 7,
        tokenStatus: "Overflow",
        overflowAmount: 3,
        monthlyAllocation: 4,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-010",
        name: "Isabel Gómez",
        email: "isabel.gomez@email.com",
        plan: "Basic",
        currentTokens: 2,
        tokenStatus: "Normal",
        monthlyAllocation: 2,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-011",
        name: "Javier Díaz",
        email: "javier.diaz@email.com",
        plan: "Premium",
        currentTokens: 4,
        tokenStatus: "Normal",
        monthlyAllocation: 4,
        status: "Active",
        nextRefill: "2024-02-01",
      },
      {
        id: "user-012",
        name: "Lucía Ramos",
        email: "lucia.ramos@email.com",
        plan: "Basic",
        currentTokens: 0,
        tokenStatus: "Empty",
        monthlyAllocation: 2,
        status: "Suspended",
        nextRefill: "2024-02-01",
      },
    ],
  }
}

export function getUserTokenHistory(userId: string) {
  // This is mock data. In a real application, you would fetch this from a database.
  type TokenHistoryEntry = { date: string; type: string; amount: number; reason: string };
  const historyData: { [key: string]: TokenHistoryEntry[] } = {
    "user-001": [
      { date: "2024-01-25", type: "Refill", amount: 4, reason: "Monthly allocation" },
      { date: "2024-01-20", type: "Added", amount: 5, reason: "Compensation for service interruption" },
      { date: "2024-01-15", type: "Deducted", amount: 2, reason: "Used for premium feature X" },
    ],
    "user-002": [
      { date: "2024-01-25", type: "Refill", amount: 2, reason: "Monthly allocation" },
      { date: "2024-01-22", type: "Deducted", amount: 1, reason: "Used for basic feature Y" },
      { date: "2024-01-10", type: "Added", amount: 3, reason: "Welcome bonus" },
    ],
    "user-003": [
      { date: "2024-01-25", type: "Refill", amount: 4, reason: "Monthly allocation" },
      { date: "2024-01-20", type: "Added", amount: 2, reason: "Manual adjustment by admin" },
    ],
    "user-004": [
      { date: "2024-01-25", type: "Refill", amount: 2, reason: "Monthly allocation" },
      { date: "2024-01-18", type: "Deducted", amount: 1, reason: "Used for basic feature Z" },
      { date: "2024-01-10", type: "Suspended", amount: 0, reason: "Account suspended due to inactivity" },
    ],
    // Add more history data for other users as needed
  }

  return historyData[userId] || []
}
